// Generated by rstantools.  Do not edit by hand.

/*
    MVbeliefupdatr is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    MVbeliefupdatr is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with MVbeliefupdatr.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_mvg_conj_uninformative_priors_sufficient_stats_lapse_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_mvg_conj_uninformative_priors_sufficient_stats_lapse");
    reader.add_event(159, 157, "end", "model_mvg_conj_uninformative_priors_sufficient_stats_lapse");
    return reader;
}
#include <stan_meta_header.hpp>
class model_mvg_conj_uninformative_priors_sufficient_stats_lapse
  : public stan::model::model_base_crtp<model_mvg_conj_uninformative_priors_sufficient_stats_lapse> {
private:
        int M;
        int L;
        int K;
        matrix_d N;
        std::vector<std::vector<vector_d> > x_mean;
        std::vector<std::vector<matrix_d> > x_ss;
        int N_test;
        std::vector<vector_d> x_test;
        std::vector<int> y_test;
        std::vector<std::vector<int> > z_test_counts;
        double tau_scale;
        double L_omega_scale;
        double sigma_kappanu;
public:
    model_mvg_conj_uninformative_priors_sufficient_stats_lapse(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_mvg_conj_uninformative_priors_sufficient_stats_lapse(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_mvg_conj_uninformative_priors_sufficient_stats_lapse_namespace::model_mvg_conj_uninformative_priors_sufficient_stats_lapse";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 20;
            context__.validate_dims("data initialization", "M", "int", context__.to_vec());
            M = int(0);
            vals_i__ = context__.vals_i("M");
            pos__ = 0;
            M = vals_i__[pos__++];
            current_statement_begin__ = 21;
            context__.validate_dims("data initialization", "L", "int", context__.to_vec());
            L = int(0);
            vals_i__ = context__.vals_i("L");
            pos__ = 0;
            L = vals_i__[pos__++];
            current_statement_begin__ = 22;
            context__.validate_dims("data initialization", "K", "int", context__.to_vec());
            K = int(0);
            vals_i__ = context__.vals_i("K");
            pos__ = 0;
            K = vals_i__[pos__++];
            current_statement_begin__ = 28;
            validate_non_negative_index("N", "M", M);
            validate_non_negative_index("N", "L", L);
            context__.validate_dims("data initialization", "N", "matrix_d", context__.to_vec(M,L));
            N = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(M, L);
            vals_r__ = context__.vals_r("N");
            pos__ = 0;
            size_t N_j_2_max__ = L;
            size_t N_j_1_max__ = M;
            for (size_t j_2__ = 0; j_2__ < N_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < N_j_1_max__; ++j_1__) {
                    N(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 29;
            validate_non_negative_index("x_mean", "K", K);
            validate_non_negative_index("x_mean", "M", M);
            validate_non_negative_index("x_mean", "L", L);
            context__.validate_dims("data initialization", "x_mean", "vector_d", context__.to_vec(M,L,K));
            x_mean = std::vector<std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > >(M, std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> >(L, Eigen::Matrix<double, Eigen::Dynamic, 1>(K)));
            vals_r__ = context__.vals_r("x_mean");
            pos__ = 0;
            size_t x_mean_j_1_max__ = K;
            size_t x_mean_k_0_max__ = M;
            size_t x_mean_k_1_max__ = L;
            for (size_t j_1__ = 0; j_1__ < x_mean_j_1_max__; ++j_1__) {
                for (size_t k_1__ = 0; k_1__ < x_mean_k_1_max__; ++k_1__) {
                    for (size_t k_0__ = 0; k_0__ < x_mean_k_0_max__; ++k_0__) {
                        x_mean[k_0__][k_1__](j_1__) = vals_r__[pos__++];
                    }
                }
            }
            current_statement_begin__ = 30;
            validate_non_negative_index("x_ss", "K", K);
            validate_non_negative_index("x_ss", "K", K);
            validate_non_negative_index("x_ss", "M", M);
            validate_non_negative_index("x_ss", "L", L);
            context__.validate_dims("data initialization", "x_ss", "matrix_d", context__.to_vec(M,L,K,K));
            x_ss = std::vector<std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > >(M, std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> >(L, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(K, K)));
            vals_r__ = context__.vals_r("x_ss");
            pos__ = 0;
            size_t x_ss_j_2_max__ = K;
            size_t x_ss_j_1_max__ = K;
            size_t x_ss_k_0_max__ = M;
            size_t x_ss_k_1_max__ = L;
            for (size_t j_2__ = 0; j_2__ < x_ss_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < x_ss_j_1_max__; ++j_1__) {
                    for (size_t k_1__ = 0; k_1__ < x_ss_k_1_max__; ++k_1__) {
                        for (size_t k_0__ = 0; k_0__ < x_ss_k_0_max__; ++k_0__) {
                            x_ss[k_0__][k_1__](j_1__, j_2__) = vals_r__[pos__++];
                        }
                    }
                }
            }
            size_t x_ss_i_0_max__ = M;
            size_t x_ss_i_1_max__ = L;
            for (size_t i_0__ = 0; i_0__ < x_ss_i_0_max__; ++i_0__) {
                for (size_t i_1__ = 0; i_1__ < x_ss_i_1_max__; ++i_1__) {
                    stan::math::check_cov_matrix(function__, "x_ss[i_0__][i_1__]", x_ss[i_0__][i_1__]);
                }
            }
            current_statement_begin__ = 32;
            context__.validate_dims("data initialization", "N_test", "int", context__.to_vec());
            N_test = int(0);
            vals_i__ = context__.vals_i("N_test");
            pos__ = 0;
            N_test = vals_i__[pos__++];
            current_statement_begin__ = 33;
            validate_non_negative_index("x_test", "K", K);
            validate_non_negative_index("x_test", "N_test", N_test);
            context__.validate_dims("data initialization", "x_test", "vector_d", context__.to_vec(N_test,K));
            x_test = std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> >(N_test, Eigen::Matrix<double, Eigen::Dynamic, 1>(K));
            vals_r__ = context__.vals_r("x_test");
            pos__ = 0;
            size_t x_test_j_1_max__ = K;
            size_t x_test_k_0_max__ = N_test;
            for (size_t j_1__ = 0; j_1__ < x_test_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < x_test_k_0_max__; ++k_0__) {
                    x_test[k_0__](j_1__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 34;
            validate_non_negative_index("y_test", "N_test", N_test);
            context__.validate_dims("data initialization", "y_test", "int", context__.to_vec(N_test));
            y_test = std::vector<int>(N_test, int(0));
            vals_i__ = context__.vals_i("y_test");
            pos__ = 0;
            size_t y_test_k_0_max__ = N_test;
            for (size_t k_0__ = 0; k_0__ < y_test_k_0_max__; ++k_0__) {
                y_test[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 35;
            validate_non_negative_index("z_test_counts", "N_test", N_test);
            validate_non_negative_index("z_test_counts", "M", M);
            context__.validate_dims("data initialization", "z_test_counts", "int", context__.to_vec(N_test,M));
            z_test_counts = std::vector<std::vector<int> >(N_test, std::vector<int>(M, int(0)));
            vals_i__ = context__.vals_i("z_test_counts");
            pos__ = 0;
            size_t z_test_counts_k_0_max__ = N_test;
            size_t z_test_counts_k_1_max__ = M;
            for (size_t k_1__ = 0; k_1__ < z_test_counts_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < z_test_counts_k_0_max__; ++k_0__) {
                    z_test_counts[k_0__][k_1__] = vals_i__[pos__++];
                }
            }
            current_statement_begin__ = 40;
            context__.validate_dims("data initialization", "tau_scale", "double", context__.to_vec());
            tau_scale = double(0);
            vals_r__ = context__.vals_r("tau_scale");
            pos__ = 0;
            tau_scale = vals_r__[pos__++];
            check_greater_or_equal(function__, "tau_scale", tau_scale, 0);
            current_statement_begin__ = 41;
            context__.validate_dims("data initialization", "L_omega_scale", "double", context__.to_vec());
            L_omega_scale = double(0);
            vals_r__ = context__.vals_r("L_omega_scale");
            pos__ = 0;
            L_omega_scale = vals_r__[pos__++];
            check_greater_or_equal(function__, "L_omega_scale", L_omega_scale, 0);
            // initialize transformed data variables
            current_statement_begin__ = 45;
            sigma_kappanu = double(0);
            stan::math::fill(sigma_kappanu, DUMMY_VAR__);
            // execute transformed data statements
            current_statement_begin__ = 47;
            stan::math::assign(sigma_kappanu, (logical_gt(max(N), 0) ? stan::math::promote_scalar<double>((max(N) * 4)) : stan::math::promote_scalar<double>(10) ));
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 52;
            num_params_r__ += 1;
            current_statement_begin__ = 53;
            num_params_r__ += 1;
            current_statement_begin__ = 55;
            validate_non_negative_index("mu_0", "K", K);
            validate_non_negative_index("mu_0", "M", M);
            num_params_r__ += (K * M);
            current_statement_begin__ = 56;
            validate_non_negative_index("mu_0_tau", "K", K);
            num_params_r__ += K;
            current_statement_begin__ = 57;
            validate_non_negative_index("mu_0_L_omega", "K", K);
            validate_non_negative_index("mu_0_L_omega", "K", K);
            num_params_r__ += ((K * (K - 1)) / 2);
            current_statement_begin__ = 59;
            validate_non_negative_index("tau_0", "K", K);
            validate_non_negative_index("tau_0", "M", M);
            num_params_r__ += (K * M);
            current_statement_begin__ = 60;
            validate_non_negative_index("L_omega_0", "K", K);
            validate_non_negative_index("L_omega_0", "K", K);
            validate_non_negative_index("L_omega_0", "M", M);
            num_params_r__ += (((K * (K - 1)) / 2) * M);
            current_statement_begin__ = 62;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_mvg_conj_uninformative_priors_sufficient_stats_lapse() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 52;
        if (!(context__.contains_r("kappa_0")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable kappa_0 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("kappa_0");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "kappa_0", "double", context__.to_vec());
        double kappa_0(0);
        kappa_0 = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(K, kappa_0);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable kappa_0: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 53;
        if (!(context__.contains_r("nu_0")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable nu_0 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("nu_0");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "nu_0", "double", context__.to_vec());
        double nu_0(0);
        nu_0 = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(K, nu_0);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable nu_0: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 55;
        if (!(context__.contains_r("mu_0")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable mu_0 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("mu_0");
        pos__ = 0U;
        validate_non_negative_index("mu_0", "K", K);
        validate_non_negative_index("mu_0", "M", M);
        context__.validate_dims("parameter initialization", "mu_0", "vector_d", context__.to_vec(M,K));
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > mu_0(M, Eigen::Matrix<double, Eigen::Dynamic, 1>(K));
        size_t mu_0_j_1_max__ = K;
        size_t mu_0_k_0_max__ = M;
        for (size_t j_1__ = 0; j_1__ < mu_0_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < mu_0_k_0_max__; ++k_0__) {
                mu_0[k_0__](j_1__) = vals_r__[pos__++];
            }
        }
        size_t mu_0_i_0_max__ = M;
        for (size_t i_0__ = 0; i_0__ < mu_0_i_0_max__; ++i_0__) {
            try {
                writer__.vector_unconstrain(mu_0[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable mu_0: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 56;
        if (!(context__.contains_r("mu_0_tau")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable mu_0_tau missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("mu_0_tau");
        pos__ = 0U;
        validate_non_negative_index("mu_0_tau", "K", K);
        context__.validate_dims("parameter initialization", "mu_0_tau", "vector_d", context__.to_vec(K));
        Eigen::Matrix<double, Eigen::Dynamic, 1> mu_0_tau(K);
        size_t mu_0_tau_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < mu_0_tau_j_1_max__; ++j_1__) {
            mu_0_tau(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, mu_0_tau);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable mu_0_tau: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 57;
        if (!(context__.contains_r("mu_0_L_omega")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable mu_0_L_omega missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("mu_0_L_omega");
        pos__ = 0U;
        validate_non_negative_index("mu_0_L_omega", "K", K);
        validate_non_negative_index("mu_0_L_omega", "K", K);
        context__.validate_dims("parameter initialization", "mu_0_L_omega", "matrix_d", context__.to_vec(K,K));
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> mu_0_L_omega(K, K);
        size_t mu_0_L_omega_j_2_max__ = K;
        size_t mu_0_L_omega_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < mu_0_L_omega_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < mu_0_L_omega_j_1_max__; ++j_1__) {
                mu_0_L_omega(j_1__, j_2__) = vals_r__[pos__++];
            }
        }
        try {
            writer__.cholesky_factor_corr_unconstrain(mu_0_L_omega);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable mu_0_L_omega: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 59;
        if (!(context__.contains_r("tau_0")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable tau_0 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("tau_0");
        pos__ = 0U;
        validate_non_negative_index("tau_0", "K", K);
        validate_non_negative_index("tau_0", "M", M);
        context__.validate_dims("parameter initialization", "tau_0", "vector_d", context__.to_vec(M,K));
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > tau_0(M, Eigen::Matrix<double, Eigen::Dynamic, 1>(K));
        size_t tau_0_j_1_max__ = K;
        size_t tau_0_k_0_max__ = M;
        for (size_t j_1__ = 0; j_1__ < tau_0_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < tau_0_k_0_max__; ++k_0__) {
                tau_0[k_0__](j_1__) = vals_r__[pos__++];
            }
        }
        size_t tau_0_i_0_max__ = M;
        for (size_t i_0__ = 0; i_0__ < tau_0_i_0_max__; ++i_0__) {
            try {
                writer__.vector_lb_unconstrain(0, tau_0[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable tau_0: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 60;
        if (!(context__.contains_r("L_omega_0")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable L_omega_0 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("L_omega_0");
        pos__ = 0U;
        validate_non_negative_index("L_omega_0", "K", K);
        validate_non_negative_index("L_omega_0", "K", K);
        validate_non_negative_index("L_omega_0", "M", M);
        context__.validate_dims("parameter initialization", "L_omega_0", "matrix_d", context__.to_vec(M,K,K));
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > L_omega_0(M, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(K, K));
        size_t L_omega_0_j_2_max__ = K;
        size_t L_omega_0_j_1_max__ = K;
        size_t L_omega_0_k_0_max__ = M;
        for (size_t j_2__ = 0; j_2__ < L_omega_0_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < L_omega_0_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < L_omega_0_k_0_max__; ++k_0__) {
                    L_omega_0[k_0__](j_1__, j_2__) = vals_r__[pos__++];
                }
            }
        }
        size_t L_omega_0_i_0_max__ = M;
        for (size_t i_0__ = 0; i_0__ < L_omega_0_i_0_max__; ++i_0__) {
            try {
                writer__.cholesky_factor_corr_unconstrain(L_omega_0[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable L_omega_0: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 62;
        if (!(context__.contains_r("lapse_rate")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lapse_rate missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lapse_rate");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "lapse_rate", "double", context__.to_vec());
        double lapse_rate(0);
        lapse_rate = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(0, 1, lapse_rate);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lapse_rate: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 52;
            local_scalar_t__ kappa_0;
            (void) kappa_0;  // dummy to suppress unused var warning
            if (jacobian__)
                kappa_0 = in__.scalar_lb_constrain(K, lp__);
            else
                kappa_0 = in__.scalar_lb_constrain(K);
            current_statement_begin__ = 53;
            local_scalar_t__ nu_0;
            (void) nu_0;  // dummy to suppress unused var warning
            if (jacobian__)
                nu_0 = in__.scalar_lb_constrain(K, lp__);
            else
                nu_0 = in__.scalar_lb_constrain(K);
            current_statement_begin__ = 55;
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > mu_0;
            size_t mu_0_d_0_max__ = M;
            mu_0.reserve(mu_0_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < mu_0_d_0_max__; ++d_0__) {
                if (jacobian__)
                    mu_0.push_back(in__.vector_constrain(K, lp__));
                else
                    mu_0.push_back(in__.vector_constrain(K));
            }
            current_statement_begin__ = 56;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> mu_0_tau;
            (void) mu_0_tau;  // dummy to suppress unused var warning
            if (jacobian__)
                mu_0_tau = in__.vector_lb_constrain(0, K, lp__);
            else
                mu_0_tau = in__.vector_lb_constrain(0, K);
            current_statement_begin__ = 57;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> mu_0_L_omega;
            (void) mu_0_L_omega;  // dummy to suppress unused var warning
            if (jacobian__)
                mu_0_L_omega = in__.cholesky_factor_corr_constrain(K, lp__);
            else
                mu_0_L_omega = in__.cholesky_factor_corr_constrain(K);
            current_statement_begin__ = 59;
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > tau_0;
            size_t tau_0_d_0_max__ = M;
            tau_0.reserve(tau_0_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < tau_0_d_0_max__; ++d_0__) {
                if (jacobian__)
                    tau_0.push_back(in__.vector_lb_constrain(0, K, lp__));
                else
                    tau_0.push_back(in__.vector_lb_constrain(0, K));
            }
            current_statement_begin__ = 60;
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> > L_omega_0;
            size_t L_omega_0_d_0_max__ = M;
            L_omega_0.reserve(L_omega_0_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < L_omega_0_d_0_max__; ++d_0__) {
                if (jacobian__)
                    L_omega_0.push_back(in__.cholesky_factor_corr_constrain(K, lp__));
                else
                    L_omega_0.push_back(in__.cholesky_factor_corr_constrain(K));
            }
            current_statement_begin__ = 62;
            local_scalar_t__ lapse_rate;
            (void) lapse_rate;  // dummy to suppress unused var warning
            if (jacobian__)
                lapse_rate = in__.scalar_lub_constrain(0, 1, lp__);
            else
                lapse_rate = in__.scalar_lub_constrain(0, 1);
            // transformed parameters
            current_statement_begin__ = 67;
            validate_non_negative_index("kappa_n", "M", M);
            validate_non_negative_index("kappa_n", "L", L);
            std::vector<std::vector<local_scalar_t__> > kappa_n(M, std::vector<local_scalar_t__>(L, local_scalar_t__(0)));
            stan::math::initialize(kappa_n, DUMMY_VAR__);
            stan::math::fill(kappa_n, DUMMY_VAR__);
            current_statement_begin__ = 68;
            validate_non_negative_index("nu_n", "M", M);
            validate_non_negative_index("nu_n", "L", L);
            std::vector<std::vector<local_scalar_t__> > nu_n(M, std::vector<local_scalar_t__>(L, local_scalar_t__(0)));
            stan::math::initialize(nu_n, DUMMY_VAR__);
            stan::math::fill(nu_n, DUMMY_VAR__);
            current_statement_begin__ = 69;
            validate_non_negative_index("mu_n", "K", K);
            validate_non_negative_index("mu_n", "M", M);
            validate_non_negative_index("mu_n", "L", L);
            std::vector<std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > > mu_n(M, std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> >(L, Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1>(K)));
            stan::math::initialize(mu_n, DUMMY_VAR__);
            stan::math::fill(mu_n, DUMMY_VAR__);
            current_statement_begin__ = 70;
            validate_non_negative_index("sigma_0", "K", K);
            validate_non_negative_index("sigma_0", "K", K);
            validate_non_negative_index("sigma_0", "M", M);
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> > sigma_0(M, Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic>(K, K));
            stan::math::initialize(sigma_0, DUMMY_VAR__);
            stan::math::fill(sigma_0, DUMMY_VAR__);
            current_statement_begin__ = 71;
            validate_non_negative_index("sigma_n", "K", K);
            validate_non_negative_index("sigma_n", "K", K);
            validate_non_negative_index("sigma_n", "M", M);
            validate_non_negative_index("sigma_n", "L", L);
            std::vector<std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> > > sigma_n(M, std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> >(L, Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic>(K, K)));
            stan::math::initialize(sigma_n, DUMMY_VAR__);
            stan::math::fill(sigma_n, DUMMY_VAR__);
            current_statement_begin__ = 72;
            validate_non_negative_index("t_scale", "K", K);
            validate_non_negative_index("t_scale", "K", K);
            validate_non_negative_index("t_scale", "M", M);
            validate_non_negative_index("t_scale", "L", L);
            std::vector<std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> > > t_scale(M, std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> >(L, Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic>(K, K)));
            stan::math::initialize(t_scale, DUMMY_VAR__);
            stan::math::fill(t_scale, DUMMY_VAR__);
            current_statement_begin__ = 74;
            validate_non_negative_index("p_test_conj", "M", M);
            validate_non_negative_index("p_test_conj", "N_test", N_test);
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > p_test_conj(N_test, Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1>(M));
            stan::math::initialize(p_test_conj, DUMMY_VAR__);
            stan::math::fill(p_test_conj, DUMMY_VAR__);
            current_statement_begin__ = 75;
            validate_non_negative_index("log_p_test_conj", "M", M);
            validate_non_negative_index("log_p_test_conj", "N_test", N_test);
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > log_p_test_conj(N_test, Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1>(M));
            stan::math::initialize(log_p_test_conj, DUMMY_VAR__);
            stan::math::fill(log_p_test_conj, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 79;
            for (int cat = 1; cat <= M; ++cat) {
                current_statement_begin__ = 81;
                stan::model::assign(sigma_0, 
                            stan::model::cons_list(stan::model::index_uni(cat), stan::model::nil_index_list()), 
                            quad_form_diag(multiply_lower_tri_self_transpose(get_base1(L_omega_0, cat, "L_omega_0", 1)), get_base1(tau_0, cat, "tau_0", 1)), 
                            "assigning variable sigma_0");
                current_statement_begin__ = 82;
                for (int subj = 1; subj <= L; ++subj) {
                    current_statement_begin__ = 83;
                    if (as_bool(logical_gt(get_base1(N, cat, subj, "N", 1), 0))) {
                        current_statement_begin__ = 84;
                        stan::model::assign(kappa_n, 
                                    stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                    (kappa_0 + get_base1(N, cat, subj, "N", 1)), 
                                    "assigning variable kappa_n");
                        current_statement_begin__ = 85;
                        stan::model::assign(nu_n, 
                                    stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                    (nu_0 + get_base1(N, cat, subj, "N", 1)), 
                                    "assigning variable nu_n");
                        current_statement_begin__ = 86;
                        stan::model::assign(mu_n, 
                                    stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                    divide(add(multiply(kappa_0, get_base1(mu_0, cat, "mu_0", 1)), multiply(get_base1(N, cat, subj, "N", 1), get_base1(get_base1(x_mean, cat, "x_mean", 1), subj, "x_mean", 2))), get_base1(get_base1(kappa_n, cat, "kappa_n", 1), subj, "kappa_n", 2)), 
                                    "assigning variable mu_n");
                        current_statement_begin__ = 88;
                        stan::model::assign(sigma_n, 
                                    stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                    subtract(add(add(get_base1(sigma_0, cat, "sigma_0", 1), get_base1(get_base1(x_ss, cat, "x_ss", 1), subj, "x_ss", 2)), multiply(multiply(kappa_0, get_base1(mu_0, cat, "mu_0", 1)), transpose(get_base1(mu_0, cat, "mu_0", 1)))), multiply(multiply(get_base1(get_base1(kappa_n, cat, "kappa_n", 1), subj, "kappa_n", 2), get_base1(get_base1(mu_n, cat, "mu_n", 1), subj, "mu_n", 2)), transpose(get_base1(get_base1(mu_n, cat, "mu_n", 1), subj, "mu_n", 2)))), 
                                    "assigning variable sigma_n");
                    } else {
                        current_statement_begin__ = 93;
                        stan::model::assign(kappa_n, 
                                    stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                    kappa_0, 
                                    "assigning variable kappa_n");
                        current_statement_begin__ = 94;
                        stan::model::assign(nu_n, 
                                    stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                    nu_0, 
                                    "assigning variable nu_n");
                        current_statement_begin__ = 95;
                        stan::model::assign(mu_n, 
                                    stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                    get_base1(mu_0, cat, "mu_0", 1), 
                                    "assigning variable mu_n");
                        current_statement_begin__ = 96;
                        stan::model::assign(sigma_n, 
                                    stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                    get_base1(sigma_0, cat, "sigma_0", 1), 
                                    "assigning variable sigma_n");
                    }
                    current_statement_begin__ = 99;
                    stan::model::assign(t_scale, 
                                stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                divide(multiply(get_base1(get_base1(sigma_n, cat, "sigma_n", 1), subj, "sigma_n", 2), (get_base1(get_base1(kappa_n, cat, "kappa_n", 1), subj, "kappa_n", 2) + 1)), (get_base1(get_base1(kappa_n, cat, "kappa_n", 1), subj, "kappa_n", 2) * ((get_base1(get_base1(nu_n, cat, "nu_n", 1), subj, "nu_n", 2) - K) + 1))), 
                                "assigning variable t_scale");
                }
            }
            current_statement_begin__ = 105;
            for (int j = 1; j <= N_test; ++j) {
                {
                current_statement_begin__ = 106;
                int subj(0);
                (void) subj;  // dummy to suppress unused var warning
                stan::math::fill(subj, std::numeric_limits<int>::min());
                current_statement_begin__ = 107;
                stan::math::assign(subj, get_base1(y_test, j, "y_test", 1));
                current_statement_begin__ = 109;
                for (int cat = 1; cat <= M; ++cat) {
                    current_statement_begin__ = 110;
                    stan::model::assign(log_p_test_conj, 
                                stan::model::cons_list(stan::model::index_uni(j), stan::model::cons_list(stan::model::index_uni(cat), stan::model::nil_index_list())), 
                                multi_student_t_log(get_base1(x_test, j, "x_test", 1), ((get_base1(get_base1(nu_n, cat, "nu_n", 1), subj, "nu_n", 2) - K) + 1), get_base1(get_base1(mu_n, cat, "mu_n", 1), subj, "mu_n", 2), get_base1(get_base1(t_scale, cat, "t_scale", 1), subj, "t_scale", 2)), 
                                "assigning variable log_p_test_conj");
                }
                current_statement_begin__ = 116;
                stan::model::assign(p_test_conj, 
                            stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()), 
                            stan::math::exp(subtract(get_base1(log_p_test_conj, j, "log_p_test_conj", 1), log_sum_exp(get_base1(log_p_test_conj, j, "log_p_test_conj", 1)))), 
                            "assigning variable p_test_conj");
                }
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 67;
            size_t kappa_n_k_0_max__ = M;
            size_t kappa_n_k_1_max__ = L;
            for (size_t k_0__ = 0; k_0__ < kappa_n_k_0_max__; ++k_0__) {
                for (size_t k_1__ = 0; k_1__ < kappa_n_k_1_max__; ++k_1__) {
                    if (stan::math::is_uninitialized(kappa_n[k_0__][k_1__])) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: kappa_n" << "[" << k_0__ << "]" << "[" << k_1__ << "]";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable kappa_n: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            size_t kappa_n_i_0_max__ = M;
            size_t kappa_n_i_1_max__ = L;
            for (size_t i_0__ = 0; i_0__ < kappa_n_i_0_max__; ++i_0__) {
                for (size_t i_1__ = 0; i_1__ < kappa_n_i_1_max__; ++i_1__) {
                    check_greater_or_equal(function__, "kappa_n[i_0__][i_1__]", kappa_n[i_0__][i_1__], K);
                }
            }
            current_statement_begin__ = 68;
            size_t nu_n_k_0_max__ = M;
            size_t nu_n_k_1_max__ = L;
            for (size_t k_0__ = 0; k_0__ < nu_n_k_0_max__; ++k_0__) {
                for (size_t k_1__ = 0; k_1__ < nu_n_k_1_max__; ++k_1__) {
                    if (stan::math::is_uninitialized(nu_n[k_0__][k_1__])) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: nu_n" << "[" << k_0__ << "]" << "[" << k_1__ << "]";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable nu_n: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            size_t nu_n_i_0_max__ = M;
            size_t nu_n_i_1_max__ = L;
            for (size_t i_0__ = 0; i_0__ < nu_n_i_0_max__; ++i_0__) {
                for (size_t i_1__ = 0; i_1__ < nu_n_i_1_max__; ++i_1__) {
                    check_greater_or_equal(function__, "nu_n[i_0__][i_1__]", nu_n[i_0__][i_1__], K);
                }
            }
            current_statement_begin__ = 69;
            size_t mu_n_k_0_max__ = M;
            size_t mu_n_k_1_max__ = L;
            size_t mu_n_j_1_max__ = K;
            for (size_t k_0__ = 0; k_0__ < mu_n_k_0_max__; ++k_0__) {
                for (size_t k_1__ = 0; k_1__ < mu_n_k_1_max__; ++k_1__) {
                    for (size_t j_1__ = 0; j_1__ < mu_n_j_1_max__; ++j_1__) {
                        if (stan::math::is_uninitialized(mu_n[k_0__][k_1__](j_1__))) {
                            std::stringstream msg__;
                            msg__ << "Undefined transformed parameter: mu_n" << "[" << k_0__ << "]" << "[" << k_1__ << "]" << "(" << j_1__ << ")";
                            stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable mu_n: ") + msg__.str()), current_statement_begin__, prog_reader__());
                        }
                    }
                }
            }
            current_statement_begin__ = 70;
            size_t sigma_0_k_0_max__ = M;
            size_t sigma_0_j_1_max__ = K;
            size_t sigma_0_j_2_max__ = K;
            for (size_t k_0__ = 0; k_0__ < sigma_0_k_0_max__; ++k_0__) {
                for (size_t j_1__ = 0; j_1__ < sigma_0_j_1_max__; ++j_1__) {
                    for (size_t j_2__ = 0; j_2__ < sigma_0_j_2_max__; ++j_2__) {
                        if (stan::math::is_uninitialized(sigma_0[k_0__](j_1__, j_2__))) {
                            std::stringstream msg__;
                            msg__ << "Undefined transformed parameter: sigma_0" << "[" << k_0__ << "]" << "(" << j_1__ << ", " << j_2__ << ")";
                            stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable sigma_0: ") + msg__.str()), current_statement_begin__, prog_reader__());
                        }
                    }
                }
            }
            size_t sigma_0_i_0_max__ = M;
            for (size_t i_0__ = 0; i_0__ < sigma_0_i_0_max__; ++i_0__) {
                stan::math::check_cov_matrix(function__, "sigma_0[i_0__]", sigma_0[i_0__]);
            }
            current_statement_begin__ = 71;
            size_t sigma_n_k_0_max__ = M;
            size_t sigma_n_k_1_max__ = L;
            size_t sigma_n_j_1_max__ = K;
            size_t sigma_n_j_2_max__ = K;
            for (size_t k_0__ = 0; k_0__ < sigma_n_k_0_max__; ++k_0__) {
                for (size_t k_1__ = 0; k_1__ < sigma_n_k_1_max__; ++k_1__) {
                    for (size_t j_1__ = 0; j_1__ < sigma_n_j_1_max__; ++j_1__) {
                        for (size_t j_2__ = 0; j_2__ < sigma_n_j_2_max__; ++j_2__) {
                            if (stan::math::is_uninitialized(sigma_n[k_0__][k_1__](j_1__, j_2__))) {
                                std::stringstream msg__;
                                msg__ << "Undefined transformed parameter: sigma_n" << "[" << k_0__ << "]" << "[" << k_1__ << "]" << "(" << j_1__ << ", " << j_2__ << ")";
                                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable sigma_n: ") + msg__.str()), current_statement_begin__, prog_reader__());
                            }
                        }
                    }
                }
            }
            size_t sigma_n_i_0_max__ = M;
            size_t sigma_n_i_1_max__ = L;
            for (size_t i_0__ = 0; i_0__ < sigma_n_i_0_max__; ++i_0__) {
                for (size_t i_1__ = 0; i_1__ < sigma_n_i_1_max__; ++i_1__) {
                    stan::math::check_cov_matrix(function__, "sigma_n[i_0__][i_1__]", sigma_n[i_0__][i_1__]);
                }
            }
            current_statement_begin__ = 72;
            size_t t_scale_k_0_max__ = M;
            size_t t_scale_k_1_max__ = L;
            size_t t_scale_j_1_max__ = K;
            size_t t_scale_j_2_max__ = K;
            for (size_t k_0__ = 0; k_0__ < t_scale_k_0_max__; ++k_0__) {
                for (size_t k_1__ = 0; k_1__ < t_scale_k_1_max__; ++k_1__) {
                    for (size_t j_1__ = 0; j_1__ < t_scale_j_1_max__; ++j_1__) {
                        for (size_t j_2__ = 0; j_2__ < t_scale_j_2_max__; ++j_2__) {
                            if (stan::math::is_uninitialized(t_scale[k_0__][k_1__](j_1__, j_2__))) {
                                std::stringstream msg__;
                                msg__ << "Undefined transformed parameter: t_scale" << "[" << k_0__ << "]" << "[" << k_1__ << "]" << "(" << j_1__ << ", " << j_2__ << ")";
                                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable t_scale: ") + msg__.str()), current_statement_begin__, prog_reader__());
                            }
                        }
                    }
                }
            }
            size_t t_scale_i_0_max__ = M;
            size_t t_scale_i_1_max__ = L;
            for (size_t i_0__ = 0; i_0__ < t_scale_i_0_max__; ++i_0__) {
                for (size_t i_1__ = 0; i_1__ < t_scale_i_1_max__; ++i_1__) {
                    stan::math::check_cov_matrix(function__, "t_scale[i_0__][i_1__]", t_scale[i_0__][i_1__]);
                }
            }
            current_statement_begin__ = 74;
            size_t p_test_conj_k_0_max__ = N_test;
            size_t p_test_conj_j_1_max__ = M;
            for (size_t k_0__ = 0; k_0__ < p_test_conj_k_0_max__; ++k_0__) {
                for (size_t j_1__ = 0; j_1__ < p_test_conj_j_1_max__; ++j_1__) {
                    if (stan::math::is_uninitialized(p_test_conj[k_0__](j_1__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: p_test_conj" << "[" << k_0__ << "]" << "(" << j_1__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable p_test_conj: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            size_t p_test_conj_i_0_max__ = N_test;
            for (size_t i_0__ = 0; i_0__ < p_test_conj_i_0_max__; ++i_0__) {
                stan::math::check_simplex(function__, "p_test_conj[i_0__]", p_test_conj[i_0__]);
            }
            current_statement_begin__ = 75;
            size_t log_p_test_conj_k_0_max__ = N_test;
            size_t log_p_test_conj_j_1_max__ = M;
            for (size_t k_0__ = 0; k_0__ < log_p_test_conj_k_0_max__; ++k_0__) {
                for (size_t j_1__ = 0; j_1__ < log_p_test_conj_j_1_max__; ++j_1__) {
                    if (stan::math::is_uninitialized(log_p_test_conj[k_0__](j_1__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: log_p_test_conj" << "[" << k_0__ << "]" << "(" << j_1__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable log_p_test_conj: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            // model body
            {
            current_statement_begin__ = 121;
            validate_non_negative_index("lapsing_probs", "M", M);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> lapsing_probs(M);
            stan::math::initialize(lapsing_probs, DUMMY_VAR__);
            stan::math::fill(lapsing_probs, DUMMY_VAR__);
            current_statement_begin__ = 123;
            stan::math::assign(lapsing_probs, rep_vector((lapse_rate / M), M));
            current_statement_begin__ = 128;
            lp_accum__.add(normal_log<propto__>(kappa_0, 0, sigma_kappanu));
            current_statement_begin__ = 129;
            lp_accum__.add(normal_log<propto__>(nu_0, 0, sigma_kappanu));
            current_statement_begin__ = 136;
            lp_accum__.add(cauchy_log<propto__>(mu_0_tau, 0, (logical_gt(tau_scale, 0) ? stan::math::promote_scalar<double>(tau_scale) : stan::math::promote_scalar<double>(5) )));
            current_statement_begin__ = 137;
            lp_accum__.add(lkj_corr_cholesky_log<propto__>(mu_0_L_omega, (logical_gt(L_omega_scale, 0) ? stan::math::promote_scalar<double>(L_omega_scale) : stan::math::promote_scalar<double>(1) )));
            current_statement_begin__ = 138;
            lp_accum__.add(multi_normal_cholesky_log<propto__>(mu_0, rep_vector(0, K), diag_pre_multiply(mu_0_tau, mu_0_L_omega)));
            current_statement_begin__ = 140;
            for (int cat = 1; cat <= M; ++cat) {
                current_statement_begin__ = 141;
                lp_accum__.add(cauchy_log<propto__>(get_base1(tau_0, cat, "tau_0", 1), 0, (logical_gt(tau_scale, 0) ? stan::math::promote_scalar<double>(tau_scale) : stan::math::promote_scalar<double>(10) )));
                current_statement_begin__ = 142;
                lp_accum__.add(lkj_corr_cholesky_log<propto__>(get_base1(L_omega_0, cat, "L_omega_0", 1), (logical_gt(L_omega_scale, 0) ? stan::math::promote_scalar<double>(L_omega_scale) : stan::math::promote_scalar<double>(1) )));
            }
            current_statement_begin__ = 145;
            for (int i = 1; i <= N_test; ++i) {
                current_statement_begin__ = 146;
                lp_accum__.add(multinomial_log<propto__>(get_base1(z_test_counts, i, "z_test_counts", 1), add(multiply(get_base1(p_test_conj, i, "p_test_conj", 1), (1 - lapse_rate)), lapsing_probs)));
            }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("kappa_0");
        names__.push_back("nu_0");
        names__.push_back("mu_0");
        names__.push_back("mu_0_tau");
        names__.push_back("mu_0_L_omega");
        names__.push_back("tau_0");
        names__.push_back("L_omega_0");
        names__.push_back("lapse_rate");
        names__.push_back("kappa_n");
        names__.push_back("nu_n");
        names__.push_back("mu_n");
        names__.push_back("sigma_0");
        names__.push_back("sigma_n");
        names__.push_back("t_scale");
        names__.push_back("p_test_conj");
        names__.push_back("log_p_test_conj");
        names__.push_back("mu_0_cor");
        names__.push_back("mu_0_cov");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(M);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(M);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(M);
        dims__.push_back(K);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(M);
        dims__.push_back(L);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(M);
        dims__.push_back(L);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(M);
        dims__.push_back(L);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(M);
        dims__.push_back(K);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(M);
        dims__.push_back(L);
        dims__.push_back(K);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(M);
        dims__.push_back(L);
        dims__.push_back(K);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_test);
        dims__.push_back(M);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_test);
        dims__.push_back(M);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dims__.push_back(K);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_mvg_conj_uninformative_priors_sufficient_stats_lapse_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double kappa_0 = in__.scalar_lb_constrain(K);
        vars__.push_back(kappa_0);
        double nu_0 = in__.scalar_lb_constrain(K);
        vars__.push_back(nu_0);
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > mu_0;
        size_t mu_0_d_0_max__ = M;
        mu_0.reserve(mu_0_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < mu_0_d_0_max__; ++d_0__) {
            mu_0.push_back(in__.vector_constrain(K));
        }
        size_t mu_0_j_1_max__ = K;
        size_t mu_0_k_0_max__ = M;
        for (size_t j_1__ = 0; j_1__ < mu_0_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < mu_0_k_0_max__; ++k_0__) {
                vars__.push_back(mu_0[k_0__](j_1__));
            }
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> mu_0_tau = in__.vector_lb_constrain(0, K);
        size_t mu_0_tau_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < mu_0_tau_j_1_max__; ++j_1__) {
            vars__.push_back(mu_0_tau(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> mu_0_L_omega = in__.cholesky_factor_corr_constrain(K);
        size_t mu_0_L_omega_j_2_max__ = K;
        size_t mu_0_L_omega_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < mu_0_L_omega_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < mu_0_L_omega_j_1_max__; ++j_1__) {
                vars__.push_back(mu_0_L_omega(j_1__, j_2__));
            }
        }
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > tau_0;
        size_t tau_0_d_0_max__ = M;
        tau_0.reserve(tau_0_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < tau_0_d_0_max__; ++d_0__) {
            tau_0.push_back(in__.vector_lb_constrain(0, K));
        }
        size_t tau_0_j_1_max__ = K;
        size_t tau_0_k_0_max__ = M;
        for (size_t j_1__ = 0; j_1__ < tau_0_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < tau_0_k_0_max__; ++k_0__) {
                vars__.push_back(tau_0[k_0__](j_1__));
            }
        }
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > L_omega_0;
        size_t L_omega_0_d_0_max__ = M;
        L_omega_0.reserve(L_omega_0_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < L_omega_0_d_0_max__; ++d_0__) {
            L_omega_0.push_back(in__.cholesky_factor_corr_constrain(K));
        }
        size_t L_omega_0_j_2_max__ = K;
        size_t L_omega_0_j_1_max__ = K;
        size_t L_omega_0_k_0_max__ = M;
        for (size_t j_2__ = 0; j_2__ < L_omega_0_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < L_omega_0_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < L_omega_0_k_0_max__; ++k_0__) {
                    vars__.push_back(L_omega_0[k_0__](j_1__, j_2__));
                }
            }
        }
        double lapse_rate = in__.scalar_lub_constrain(0, 1);
        vars__.push_back(lapse_rate);
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 67;
            validate_non_negative_index("kappa_n", "M", M);
            validate_non_negative_index("kappa_n", "L", L);
            std::vector<std::vector<double> > kappa_n(M, std::vector<double>(L, double(0)));
            stan::math::initialize(kappa_n, DUMMY_VAR__);
            stan::math::fill(kappa_n, DUMMY_VAR__);
            current_statement_begin__ = 68;
            validate_non_negative_index("nu_n", "M", M);
            validate_non_negative_index("nu_n", "L", L);
            std::vector<std::vector<double> > nu_n(M, std::vector<double>(L, double(0)));
            stan::math::initialize(nu_n, DUMMY_VAR__);
            stan::math::fill(nu_n, DUMMY_VAR__);
            current_statement_begin__ = 69;
            validate_non_negative_index("mu_n", "K", K);
            validate_non_negative_index("mu_n", "M", M);
            validate_non_negative_index("mu_n", "L", L);
            std::vector<std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > > mu_n(M, std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> >(L, Eigen::Matrix<double, Eigen::Dynamic, 1>(K)));
            stan::math::initialize(mu_n, DUMMY_VAR__);
            stan::math::fill(mu_n, DUMMY_VAR__);
            current_statement_begin__ = 70;
            validate_non_negative_index("sigma_0", "K", K);
            validate_non_negative_index("sigma_0", "K", K);
            validate_non_negative_index("sigma_0", "M", M);
            std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > sigma_0(M, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(K, K));
            stan::math::initialize(sigma_0, DUMMY_VAR__);
            stan::math::fill(sigma_0, DUMMY_VAR__);
            current_statement_begin__ = 71;
            validate_non_negative_index("sigma_n", "K", K);
            validate_non_negative_index("sigma_n", "K", K);
            validate_non_negative_index("sigma_n", "M", M);
            validate_non_negative_index("sigma_n", "L", L);
            std::vector<std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > > sigma_n(M, std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> >(L, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(K, K)));
            stan::math::initialize(sigma_n, DUMMY_VAR__);
            stan::math::fill(sigma_n, DUMMY_VAR__);
            current_statement_begin__ = 72;
            validate_non_negative_index("t_scale", "K", K);
            validate_non_negative_index("t_scale", "K", K);
            validate_non_negative_index("t_scale", "M", M);
            validate_non_negative_index("t_scale", "L", L);
            std::vector<std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > > t_scale(M, std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> >(L, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(K, K)));
            stan::math::initialize(t_scale, DUMMY_VAR__);
            stan::math::fill(t_scale, DUMMY_VAR__);
            current_statement_begin__ = 74;
            validate_non_negative_index("p_test_conj", "M", M);
            validate_non_negative_index("p_test_conj", "N_test", N_test);
            std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > p_test_conj(N_test, Eigen::Matrix<double, Eigen::Dynamic, 1>(M));
            stan::math::initialize(p_test_conj, DUMMY_VAR__);
            stan::math::fill(p_test_conj, DUMMY_VAR__);
            current_statement_begin__ = 75;
            validate_non_negative_index("log_p_test_conj", "M", M);
            validate_non_negative_index("log_p_test_conj", "N_test", N_test);
            std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > log_p_test_conj(N_test, Eigen::Matrix<double, Eigen::Dynamic, 1>(M));
            stan::math::initialize(log_p_test_conj, DUMMY_VAR__);
            stan::math::fill(log_p_test_conj, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 79;
            for (int cat = 1; cat <= M; ++cat) {
                current_statement_begin__ = 81;
                stan::model::assign(sigma_0, 
                            stan::model::cons_list(stan::model::index_uni(cat), stan::model::nil_index_list()), 
                            quad_form_diag(multiply_lower_tri_self_transpose(get_base1(L_omega_0, cat, "L_omega_0", 1)), get_base1(tau_0, cat, "tau_0", 1)), 
                            "assigning variable sigma_0");
                current_statement_begin__ = 82;
                for (int subj = 1; subj <= L; ++subj) {
                    current_statement_begin__ = 83;
                    if (as_bool(logical_gt(get_base1(N, cat, subj, "N", 1), 0))) {
                        current_statement_begin__ = 84;
                        stan::model::assign(kappa_n, 
                                    stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                    (kappa_0 + get_base1(N, cat, subj, "N", 1)), 
                                    "assigning variable kappa_n");
                        current_statement_begin__ = 85;
                        stan::model::assign(nu_n, 
                                    stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                    (nu_0 + get_base1(N, cat, subj, "N", 1)), 
                                    "assigning variable nu_n");
                        current_statement_begin__ = 86;
                        stan::model::assign(mu_n, 
                                    stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                    divide(add(multiply(kappa_0, get_base1(mu_0, cat, "mu_0", 1)), multiply(get_base1(N, cat, subj, "N", 1), get_base1(get_base1(x_mean, cat, "x_mean", 1), subj, "x_mean", 2))), get_base1(get_base1(kappa_n, cat, "kappa_n", 1), subj, "kappa_n", 2)), 
                                    "assigning variable mu_n");
                        current_statement_begin__ = 88;
                        stan::model::assign(sigma_n, 
                                    stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                    subtract(add(add(get_base1(sigma_0, cat, "sigma_0", 1), get_base1(get_base1(x_ss, cat, "x_ss", 1), subj, "x_ss", 2)), multiply(multiply(kappa_0, get_base1(mu_0, cat, "mu_0", 1)), transpose(get_base1(mu_0, cat, "mu_0", 1)))), multiply(multiply(get_base1(get_base1(kappa_n, cat, "kappa_n", 1), subj, "kappa_n", 2), get_base1(get_base1(mu_n, cat, "mu_n", 1), subj, "mu_n", 2)), transpose(get_base1(get_base1(mu_n, cat, "mu_n", 1), subj, "mu_n", 2)))), 
                                    "assigning variable sigma_n");
                    } else {
                        current_statement_begin__ = 93;
                        stan::model::assign(kappa_n, 
                                    stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                    kappa_0, 
                                    "assigning variable kappa_n");
                        current_statement_begin__ = 94;
                        stan::model::assign(nu_n, 
                                    stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                    nu_0, 
                                    "assigning variable nu_n");
                        current_statement_begin__ = 95;
                        stan::model::assign(mu_n, 
                                    stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                    get_base1(mu_0, cat, "mu_0", 1), 
                                    "assigning variable mu_n");
                        current_statement_begin__ = 96;
                        stan::model::assign(sigma_n, 
                                    stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                    get_base1(sigma_0, cat, "sigma_0", 1), 
                                    "assigning variable sigma_n");
                    }
                    current_statement_begin__ = 99;
                    stan::model::assign(t_scale, 
                                stan::model::cons_list(stan::model::index_uni(cat), stan::model::cons_list(stan::model::index_uni(subj), stan::model::nil_index_list())), 
                                divide(multiply(get_base1(get_base1(sigma_n, cat, "sigma_n", 1), subj, "sigma_n", 2), (get_base1(get_base1(kappa_n, cat, "kappa_n", 1), subj, "kappa_n", 2) + 1)), (get_base1(get_base1(kappa_n, cat, "kappa_n", 1), subj, "kappa_n", 2) * ((get_base1(get_base1(nu_n, cat, "nu_n", 1), subj, "nu_n", 2) - K) + 1))), 
                                "assigning variable t_scale");
                }
            }
            current_statement_begin__ = 105;
            for (int j = 1; j <= N_test; ++j) {
                {
                current_statement_begin__ = 106;
                int subj(0);
                (void) subj;  // dummy to suppress unused var warning
                stan::math::fill(subj, std::numeric_limits<int>::min());
                current_statement_begin__ = 107;
                stan::math::assign(subj, get_base1(y_test, j, "y_test", 1));
                current_statement_begin__ = 109;
                for (int cat = 1; cat <= M; ++cat) {
                    current_statement_begin__ = 110;
                    stan::model::assign(log_p_test_conj, 
                                stan::model::cons_list(stan::model::index_uni(j), stan::model::cons_list(stan::model::index_uni(cat), stan::model::nil_index_list())), 
                                multi_student_t_log(get_base1(x_test, j, "x_test", 1), ((get_base1(get_base1(nu_n, cat, "nu_n", 1), subj, "nu_n", 2) - K) + 1), get_base1(get_base1(mu_n, cat, "mu_n", 1), subj, "mu_n", 2), get_base1(get_base1(t_scale, cat, "t_scale", 1), subj, "t_scale", 2)), 
                                "assigning variable log_p_test_conj");
                }
                current_statement_begin__ = 116;
                stan::model::assign(p_test_conj, 
                            stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()), 
                            stan::math::exp(subtract(get_base1(log_p_test_conj, j, "log_p_test_conj", 1), log_sum_exp(get_base1(log_p_test_conj, j, "log_p_test_conj", 1)))), 
                            "assigning variable p_test_conj");
                }
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 67;
            size_t kappa_n_i_0_max__ = M;
            size_t kappa_n_i_1_max__ = L;
            for (size_t i_0__ = 0; i_0__ < kappa_n_i_0_max__; ++i_0__) {
                for (size_t i_1__ = 0; i_1__ < kappa_n_i_1_max__; ++i_1__) {
                    check_greater_or_equal(function__, "kappa_n[i_0__][i_1__]", kappa_n[i_0__][i_1__], K);
                }
            }
            current_statement_begin__ = 68;
            size_t nu_n_i_0_max__ = M;
            size_t nu_n_i_1_max__ = L;
            for (size_t i_0__ = 0; i_0__ < nu_n_i_0_max__; ++i_0__) {
                for (size_t i_1__ = 0; i_1__ < nu_n_i_1_max__; ++i_1__) {
                    check_greater_or_equal(function__, "nu_n[i_0__][i_1__]", nu_n[i_0__][i_1__], K);
                }
            }
            current_statement_begin__ = 70;
            size_t sigma_0_i_0_max__ = M;
            for (size_t i_0__ = 0; i_0__ < sigma_0_i_0_max__; ++i_0__) {
                stan::math::check_cov_matrix(function__, "sigma_0[i_0__]", sigma_0[i_0__]);
            }
            current_statement_begin__ = 71;
            size_t sigma_n_i_0_max__ = M;
            size_t sigma_n_i_1_max__ = L;
            for (size_t i_0__ = 0; i_0__ < sigma_n_i_0_max__; ++i_0__) {
                for (size_t i_1__ = 0; i_1__ < sigma_n_i_1_max__; ++i_1__) {
                    stan::math::check_cov_matrix(function__, "sigma_n[i_0__][i_1__]", sigma_n[i_0__][i_1__]);
                }
            }
            current_statement_begin__ = 72;
            size_t t_scale_i_0_max__ = M;
            size_t t_scale_i_1_max__ = L;
            for (size_t i_0__ = 0; i_0__ < t_scale_i_0_max__; ++i_0__) {
                for (size_t i_1__ = 0; i_1__ < t_scale_i_1_max__; ++i_1__) {
                    stan::math::check_cov_matrix(function__, "t_scale[i_0__][i_1__]", t_scale[i_0__][i_1__]);
                }
            }
            current_statement_begin__ = 74;
            size_t p_test_conj_i_0_max__ = N_test;
            for (size_t i_0__ = 0; i_0__ < p_test_conj_i_0_max__; ++i_0__) {
                stan::math::check_simplex(function__, "p_test_conj[i_0__]", p_test_conj[i_0__]);
            }
            // write transformed parameters
            if (include_tparams__) {
                size_t kappa_n_k_0_max__ = M;
                size_t kappa_n_k_1_max__ = L;
                for (size_t k_1__ = 0; k_1__ < kappa_n_k_1_max__; ++k_1__) {
                    for (size_t k_0__ = 0; k_0__ < kappa_n_k_0_max__; ++k_0__) {
                        vars__.push_back(kappa_n[k_0__][k_1__]);
                    }
                }
                size_t nu_n_k_0_max__ = M;
                size_t nu_n_k_1_max__ = L;
                for (size_t k_1__ = 0; k_1__ < nu_n_k_1_max__; ++k_1__) {
                    for (size_t k_0__ = 0; k_0__ < nu_n_k_0_max__; ++k_0__) {
                        vars__.push_back(nu_n[k_0__][k_1__]);
                    }
                }
                size_t mu_n_j_1_max__ = K;
                size_t mu_n_k_0_max__ = M;
                size_t mu_n_k_1_max__ = L;
                for (size_t j_1__ = 0; j_1__ < mu_n_j_1_max__; ++j_1__) {
                    for (size_t k_1__ = 0; k_1__ < mu_n_k_1_max__; ++k_1__) {
                        for (size_t k_0__ = 0; k_0__ < mu_n_k_0_max__; ++k_0__) {
                            vars__.push_back(mu_n[k_0__][k_1__](j_1__));
                        }
                    }
                }
                size_t sigma_0_j_2_max__ = K;
                size_t sigma_0_j_1_max__ = K;
                size_t sigma_0_k_0_max__ = M;
                for (size_t j_2__ = 0; j_2__ < sigma_0_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < sigma_0_j_1_max__; ++j_1__) {
                        for (size_t k_0__ = 0; k_0__ < sigma_0_k_0_max__; ++k_0__) {
                            vars__.push_back(sigma_0[k_0__](j_1__, j_2__));
                        }
                    }
                }
                size_t sigma_n_j_2_max__ = K;
                size_t sigma_n_j_1_max__ = K;
                size_t sigma_n_k_0_max__ = M;
                size_t sigma_n_k_1_max__ = L;
                for (size_t j_2__ = 0; j_2__ < sigma_n_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < sigma_n_j_1_max__; ++j_1__) {
                        for (size_t k_1__ = 0; k_1__ < sigma_n_k_1_max__; ++k_1__) {
                            for (size_t k_0__ = 0; k_0__ < sigma_n_k_0_max__; ++k_0__) {
                                vars__.push_back(sigma_n[k_0__][k_1__](j_1__, j_2__));
                            }
                        }
                    }
                }
                size_t t_scale_j_2_max__ = K;
                size_t t_scale_j_1_max__ = K;
                size_t t_scale_k_0_max__ = M;
                size_t t_scale_k_1_max__ = L;
                for (size_t j_2__ = 0; j_2__ < t_scale_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < t_scale_j_1_max__; ++j_1__) {
                        for (size_t k_1__ = 0; k_1__ < t_scale_k_1_max__; ++k_1__) {
                            for (size_t k_0__ = 0; k_0__ < t_scale_k_0_max__; ++k_0__) {
                                vars__.push_back(t_scale[k_0__][k_1__](j_1__, j_2__));
                            }
                        }
                    }
                }
                size_t p_test_conj_j_1_max__ = M;
                size_t p_test_conj_k_0_max__ = N_test;
                for (size_t j_1__ = 0; j_1__ < p_test_conj_j_1_max__; ++j_1__) {
                    for (size_t k_0__ = 0; k_0__ < p_test_conj_k_0_max__; ++k_0__) {
                        vars__.push_back(p_test_conj[k_0__](j_1__));
                    }
                }
                size_t log_p_test_conj_j_1_max__ = M;
                size_t log_p_test_conj_k_0_max__ = N_test;
                for (size_t j_1__ = 0; j_1__ < log_p_test_conj_j_1_max__; ++j_1__) {
                    for (size_t k_0__ = 0; k_0__ < log_p_test_conj_k_0_max__; ++k_0__) {
                        vars__.push_back(log_p_test_conj[k_0__](j_1__));
                    }
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 152;
            validate_non_negative_index("mu_0_cor", "K", K);
            validate_non_negative_index("mu_0_cor", "K", K);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> mu_0_cor(K, K);
            stan::math::initialize(mu_0_cor, DUMMY_VAR__);
            stan::math::fill(mu_0_cor, DUMMY_VAR__);
            current_statement_begin__ = 153;
            validate_non_negative_index("mu_0_cov", "K", K);
            validate_non_negative_index("mu_0_cov", "K", K);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> mu_0_cov(K, K);
            stan::math::initialize(mu_0_cov, DUMMY_VAR__);
            stan::math::fill(mu_0_cov, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 155;
            stan::math::assign(mu_0_cor, multiply_lower_tri_self_transpose(mu_0_L_omega));
            current_statement_begin__ = 156;
            stan::math::assign(mu_0_cov, quad_form_diag(mu_0_cor, mu_0_tau));
            // validate, write generated quantities
            current_statement_begin__ = 152;
            size_t mu_0_cor_j_2_max__ = K;
            size_t mu_0_cor_j_1_max__ = K;
            for (size_t j_2__ = 0; j_2__ < mu_0_cor_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < mu_0_cor_j_1_max__; ++j_1__) {
                    vars__.push_back(mu_0_cor(j_1__, j_2__));
                }
            }
            current_statement_begin__ = 153;
            size_t mu_0_cov_j_2_max__ = K;
            size_t mu_0_cov_j_1_max__ = K;
            for (size_t j_2__ = 0; j_2__ < mu_0_cov_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < mu_0_cov_j_1_max__; ++j_1__) {
                    vars__.push_back(mu_0_cov(j_1__, j_2__));
                }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_mvg_conj_uninformative_priors_sufficient_stats_lapse";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "kappa_0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "nu_0";
        param_names__.push_back(param_name_stream__.str());
        size_t mu_0_j_1_max__ = K;
        size_t mu_0_k_0_max__ = M;
        for (size_t j_1__ = 0; j_1__ < mu_0_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < mu_0_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "mu_0" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t mu_0_tau_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < mu_0_tau_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "mu_0_tau" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t mu_0_L_omega_j_2_max__ = K;
        size_t mu_0_L_omega_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < mu_0_L_omega_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < mu_0_L_omega_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "mu_0_L_omega" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t tau_0_j_1_max__ = K;
        size_t tau_0_k_0_max__ = M;
        for (size_t j_1__ = 0; j_1__ < tau_0_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < tau_0_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "tau_0" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t L_omega_0_j_2_max__ = K;
        size_t L_omega_0_j_1_max__ = K;
        size_t L_omega_0_k_0_max__ = M;
        for (size_t j_2__ = 0; j_2__ < L_omega_0_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < L_omega_0_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < L_omega_0_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "L_omega_0" << '.' << k_0__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "lapse_rate";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t kappa_n_k_0_max__ = M;
            size_t kappa_n_k_1_max__ = L;
            for (size_t k_1__ = 0; k_1__ < kappa_n_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < kappa_n_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "kappa_n" << '.' << k_0__ + 1 << '.' << k_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t nu_n_k_0_max__ = M;
            size_t nu_n_k_1_max__ = L;
            for (size_t k_1__ = 0; k_1__ < nu_n_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < nu_n_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "nu_n" << '.' << k_0__ + 1 << '.' << k_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t mu_n_j_1_max__ = K;
            size_t mu_n_k_0_max__ = M;
            size_t mu_n_k_1_max__ = L;
            for (size_t j_1__ = 0; j_1__ < mu_n_j_1_max__; ++j_1__) {
                for (size_t k_1__ = 0; k_1__ < mu_n_k_1_max__; ++k_1__) {
                    for (size_t k_0__ = 0; k_0__ < mu_n_k_0_max__; ++k_0__) {
                        param_name_stream__.str(std::string());
                        param_name_stream__ << "mu_n" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << j_1__ + 1;
                        param_names__.push_back(param_name_stream__.str());
                    }
                }
            }
            size_t sigma_0_j_2_max__ = K;
            size_t sigma_0_j_1_max__ = K;
            size_t sigma_0_k_0_max__ = M;
            for (size_t j_2__ = 0; j_2__ < sigma_0_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < sigma_0_j_1_max__; ++j_1__) {
                    for (size_t k_0__ = 0; k_0__ < sigma_0_k_0_max__; ++k_0__) {
                        param_name_stream__.str(std::string());
                        param_name_stream__ << "sigma_0" << '.' << k_0__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                        param_names__.push_back(param_name_stream__.str());
                    }
                }
            }
            size_t sigma_n_j_2_max__ = K;
            size_t sigma_n_j_1_max__ = K;
            size_t sigma_n_k_0_max__ = M;
            size_t sigma_n_k_1_max__ = L;
            for (size_t j_2__ = 0; j_2__ < sigma_n_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < sigma_n_j_1_max__; ++j_1__) {
                    for (size_t k_1__ = 0; k_1__ < sigma_n_k_1_max__; ++k_1__) {
                        for (size_t k_0__ = 0; k_0__ < sigma_n_k_0_max__; ++k_0__) {
                            param_name_stream__.str(std::string());
                            param_name_stream__ << "sigma_n" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                            param_names__.push_back(param_name_stream__.str());
                        }
                    }
                }
            }
            size_t t_scale_j_2_max__ = K;
            size_t t_scale_j_1_max__ = K;
            size_t t_scale_k_0_max__ = M;
            size_t t_scale_k_1_max__ = L;
            for (size_t j_2__ = 0; j_2__ < t_scale_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < t_scale_j_1_max__; ++j_1__) {
                    for (size_t k_1__ = 0; k_1__ < t_scale_k_1_max__; ++k_1__) {
                        for (size_t k_0__ = 0; k_0__ < t_scale_k_0_max__; ++k_0__) {
                            param_name_stream__.str(std::string());
                            param_name_stream__ << "t_scale" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                            param_names__.push_back(param_name_stream__.str());
                        }
                    }
                }
            }
            size_t p_test_conj_j_1_max__ = M;
            size_t p_test_conj_k_0_max__ = N_test;
            for (size_t j_1__ = 0; j_1__ < p_test_conj_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < p_test_conj_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "p_test_conj" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t log_p_test_conj_j_1_max__ = M;
            size_t log_p_test_conj_k_0_max__ = N_test;
            for (size_t j_1__ = 0; j_1__ < log_p_test_conj_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < log_p_test_conj_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "log_p_test_conj" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        if (!include_gqs__) return;
        size_t mu_0_cor_j_2_max__ = K;
        size_t mu_0_cor_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < mu_0_cor_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < mu_0_cor_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "mu_0_cor" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t mu_0_cov_j_2_max__ = K;
        size_t mu_0_cov_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < mu_0_cov_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < mu_0_cov_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "mu_0_cov" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "kappa_0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "nu_0";
        param_names__.push_back(param_name_stream__.str());
        size_t mu_0_j_1_max__ = K;
        size_t mu_0_k_0_max__ = M;
        for (size_t j_1__ = 0; j_1__ < mu_0_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < mu_0_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "mu_0" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t mu_0_tau_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < mu_0_tau_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "mu_0_tau" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t mu_0_L_omega_j_1_max__ = ((K * (K - 1)) / 2);
        for (size_t j_1__ = 0; j_1__ < mu_0_L_omega_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "mu_0_L_omega" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t tau_0_j_1_max__ = K;
        size_t tau_0_k_0_max__ = M;
        for (size_t j_1__ = 0; j_1__ < tau_0_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < tau_0_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "tau_0" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t L_omega_0_j_1_max__ = ((K * (K - 1)) / 2);
        size_t L_omega_0_k_0_max__ = M;
        for (size_t j_1__ = 0; j_1__ < L_omega_0_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < L_omega_0_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "L_omega_0" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "lapse_rate";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t kappa_n_k_0_max__ = M;
            size_t kappa_n_k_1_max__ = L;
            for (size_t k_1__ = 0; k_1__ < kappa_n_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < kappa_n_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "kappa_n" << '.' << k_0__ + 1 << '.' << k_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t nu_n_k_0_max__ = M;
            size_t nu_n_k_1_max__ = L;
            for (size_t k_1__ = 0; k_1__ < nu_n_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < nu_n_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "nu_n" << '.' << k_0__ + 1 << '.' << k_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t mu_n_j_1_max__ = K;
            size_t mu_n_k_0_max__ = M;
            size_t mu_n_k_1_max__ = L;
            for (size_t j_1__ = 0; j_1__ < mu_n_j_1_max__; ++j_1__) {
                for (size_t k_1__ = 0; k_1__ < mu_n_k_1_max__; ++k_1__) {
                    for (size_t k_0__ = 0; k_0__ < mu_n_k_0_max__; ++k_0__) {
                        param_name_stream__.str(std::string());
                        param_name_stream__ << "mu_n" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << j_1__ + 1;
                        param_names__.push_back(param_name_stream__.str());
                    }
                }
            }
            size_t sigma_0_j_1_max__ = (K + ((K * (K - 1)) / 2));
            size_t sigma_0_k_0_max__ = M;
            for (size_t j_1__ = 0; j_1__ < sigma_0_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < sigma_0_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "sigma_0" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t sigma_n_j_1_max__ = (K + ((K * (K - 1)) / 2));
            size_t sigma_n_k_0_max__ = M;
            size_t sigma_n_k_1_max__ = L;
            for (size_t j_1__ = 0; j_1__ < sigma_n_j_1_max__; ++j_1__) {
                for (size_t k_1__ = 0; k_1__ < sigma_n_k_1_max__; ++k_1__) {
                    for (size_t k_0__ = 0; k_0__ < sigma_n_k_0_max__; ++k_0__) {
                        param_name_stream__.str(std::string());
                        param_name_stream__ << "sigma_n" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << j_1__ + 1;
                        param_names__.push_back(param_name_stream__.str());
                    }
                }
            }
            size_t t_scale_j_1_max__ = (K + ((K * (K - 1)) / 2));
            size_t t_scale_k_0_max__ = M;
            size_t t_scale_k_1_max__ = L;
            for (size_t j_1__ = 0; j_1__ < t_scale_j_1_max__; ++j_1__) {
                for (size_t k_1__ = 0; k_1__ < t_scale_k_1_max__; ++k_1__) {
                    for (size_t k_0__ = 0; k_0__ < t_scale_k_0_max__; ++k_0__) {
                        param_name_stream__.str(std::string());
                        param_name_stream__ << "t_scale" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << j_1__ + 1;
                        param_names__.push_back(param_name_stream__.str());
                    }
                }
            }
            size_t p_test_conj_j_1_max__ = (M - 1);
            size_t p_test_conj_k_0_max__ = N_test;
            for (size_t j_1__ = 0; j_1__ < p_test_conj_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < p_test_conj_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "p_test_conj" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t log_p_test_conj_j_1_max__ = M;
            size_t log_p_test_conj_k_0_max__ = N_test;
            for (size_t j_1__ = 0; j_1__ < log_p_test_conj_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < log_p_test_conj_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "log_p_test_conj" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        if (!include_gqs__) return;
        size_t mu_0_cor_j_2_max__ = K;
        size_t mu_0_cor_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < mu_0_cor_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < mu_0_cor_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "mu_0_cor" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t mu_0_cov_j_2_max__ = K;
        size_t mu_0_cov_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < mu_0_cov_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < mu_0_cov_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "mu_0_cov" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
    }
}; // model
}  // namespace
typedef model_mvg_conj_uninformative_priors_sufficient_stats_lapse_namespace::model_mvg_conj_uninformative_priors_sufficient_stats_lapse stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
